"""empty message

Revision ID: a50f975a1c4b
Revises: 
Create Date: 2020-02-24 16:05:02.815074

"""
from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision = 'a50f975a1c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='自增id'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False, comment='更新时间'),
    sa.Column('delete_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=256), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=32), nullable=False, comment='邮箱'),
    sa.Column('sex', app.db.models.IntEnum(), nullable=False, comment='性别'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_create_time'), 'user', ['create_time'], unique=False)
    op.create_index(op.f('ix_user_delete_time'), 'user', ['delete_time'], unique=False)
    op.create_index(op.f('ix_user_update_time'), 'user', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_update_time'), table_name='user')
    op.drop_index(op.f('ix_user_delete_time'), table_name='user')
    op.drop_index(op.f('ix_user_create_time'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
